-- Script de creación de la BD en H2

DROP TABLE IF EXISTS PHONE;
DROP TABLE IF EXISTS USERS;

-- Tabla de usuarios
CREATE TABLE USERS (
    ID UUID PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATED TIMESTAMP,
    MODIFIED TIMESTAMP,
    LAST_LOGIN TIMESTAMP,
    TOKEN VARCHAR(512),
    IS_ACTIVE BOOLEAN
);

-- Tabla de teléfonos
CREATE TABLE PHONE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NUMBER VARCHAR(20),
    CITYCODE VARCHAR(10),
    COUNTRYCODE VARCHAR(10),
    USER_ID UUID NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USERS(id)
);
